import "../styles/globals.css";
import Header from "./Header";
import ContactInfo from "./contact/ContactInfo";

import SlideshowProvider from "./context";
import { oswald } from "./fonts";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <title>Alexia Planas Lee</title>
      </head>
      <body className={`${oswald.className} relative`}>
        <Header />
        <SlideshowProvider>
          <div className="w-full text-center relative max-w-3xl mx-auto px-4">{children}</div>
        </SlideshowProvider>
        <ContactInfo />
      </body>
    </html>
  );
}
