import "../styles/globals.css";
import SlideshowProvider from "./context";
import { oswald } from "./fonts";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <title>Alexia Planas Lee</title>
      </head>
      <body className={`${oswald.className} relative`}>
        <SlideshowProvider>{children}</SlideshowProvider>
      </body>
    </html>
  );
}
